using System.Text;
using System.Text.Json;
using Clinic_System.Data;
using Microsoft.EntityFrameworkCore;

namespace Clinic_System.Services
{
    public class AiSummaryService
    {
        private readonly AppDbContext _context;
        private readonly IConfiguration _config;
        private readonly HttpClient _httpClient;

        public AiSummaryService(AppDbContext context, IConfiguration config, HttpClient httpClient)
        {
            _context = context;
            _config = config;
            _httpClient = httpClient;
        }

        public async Task<string> GetPatientHistorySummaryAsync(int patientId)
        {
            // 1. Fetch last 8 medical records for the patient via Appointment relation
            var records = await _context.Set<Models.MedicalRecord>()
                .Include(r => r.Appointment)
                .Where(r => r.Appointment != null && r.Appointment.PatientId == patientId)
                .OrderByDescending(r => r.Id)
                .Take(8)
                .Select(r => new
                {
                    r.Complaint,
                    r.Diagnosis,
                    r.Prescription
                })
                .ToListAsync();

            if (!records.Any())
            {
                return "No previous medical records found for this patient to summarize.\n\n** Disclaimer: This summary is generated by AI and is NOT a medical diagnosis. **";
            }

            // 2. Build system context from fetched database records
            var historyText = string.Join("\n", records.Select((r, i) =>
                $"Visit {i + 1}: Complaint: {r.Complaint}, Diagnosis: {r.Diagnosis}, Prescription: {r.Prescription}"));

            var prompt = $@"You are a medical assistant summarizing patient history for the attending doctor.
                            Summarize the following last {records.Count} past clinic visits into a concise, professional 5-line medical briefing in English:

                            {historyText}

                            MANDATORY RULE: You MUST end the response with this exact line at the very bottom:
                            * Disclaimer: This summary is generated by AI and is NOT a medical diagnosis. *";

            // 3. Call Gemini API using gemini-3.6-flash
            var apiKey = _config["GeminiSettings:ApiKey"];
            if (string.IsNullOrEmpty(apiKey))
            {
                return "Error: API Key not found in configuration settings.\n\n** Disclaimer: This summary is generated by AI and is NOT a medical diagnosis. **";
            }

            var requestUrl = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key={apiKey}";

            var requestBody = new
            {
                contents = new[]
                {
                    new { parts = new[] { new { text = prompt } } }
                }
            };

            var jsonContent = new StringContent(JsonSerializer.Serialize(requestBody), Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync(requestUrl, jsonContent);

            if (!response.IsSuccessStatusCode)
            {
                var errorDetails = await response.Content.ReadAsStringAsync();
                return $"Error communicating with AI service (Status: {response.StatusCode}).\nDetails: {errorDetails}\n\n** Disclaimer: This summary is generated by AI and is NOT a medical diagnosis. **";
            }

            var responseJson = await response.Content.ReadAsStringAsync();
            using var doc = JsonDocument.Parse(responseJson);

            var aiSummary = doc.RootElement
                .GetProperty("candidates")[0]
                .GetProperty("content")
                .GetProperty("parts")[0]
                .GetProperty("text")
                .GetString();

            return aiSummary ?? "Failed to generate AI summary.";
        }
    }
}